<a href="https://colab.research.google.com/github/SJhawar1010/Reinforcement-Learning/blob/main/Satyam_554_RL_Lab7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
size = 5
g = 0.8
a = 0.1

In [3]:
V = np.zeros((size, size))

rewards = np.zeros((size, size))
rewards[3, 3] = 1

actions = {'up': (-1, 0), 'down': (1, 0), 'left': (0, -1), 'right': (0, 1)}


In [4]:
def is_valid_move(x, y):
    return 0 <= x < size and 0 <= y < size

In [5]:
def simulate_episode():
    state = (np.random.randint(0, size), np.random.randint(0, size))
    while state == (3, 3):
        state = (np.random.randint(0, size), np.random.randint(0, size))

    steps = 0
    while state != (3, 3):
        steps += 1
        x, y = state

        action = np.random.choice(list(actions.keys()))
        dx, dy = actions[action]
        next_state = (x + dx, y + dy)

        if not is_valid_move(next_state[0], next_state[1]):
            next_state = state

        reward = rewards[next_state]
        V[x, y] += a * (reward + g * V[next_state] - V[x, y])

        state = next_state

    print(f"Episode ended in {steps} steps")

In [6]:
episodes = 50
for episode in range(episodes):
    simulate_episode()

Episode ended in 46 steps
Episode ended in 58 steps
Episode ended in 160 steps
Episode ended in 34 steps
Episode ended in 1 steps
Episode ended in 8 steps
Episode ended in 12 steps
Episode ended in 114 steps
Episode ended in 82 steps
Episode ended in 35 steps
Episode ended in 38 steps
Episode ended in 22 steps
Episode ended in 38 steps
Episode ended in 4 steps
Episode ended in 53 steps
Episode ended in 10 steps
Episode ended in 103 steps
Episode ended in 40 steps
Episode ended in 26 steps
Episode ended in 151 steps
Episode ended in 157 steps
Episode ended in 75 steps
Episode ended in 23 steps
Episode ended in 37 steps
Episode ended in 28 steps
Episode ended in 91 steps
Episode ended in 107 steps
Episode ended in 32 steps
Episode ended in 70 steps
Episode ended in 41 steps
Episode ended in 10 steps
Episode ended in 34 steps
Episode ended in 92 steps
Episode ended in 52 steps
Episode ended in 2 steps
Episode ended in 41 steps
Episode ended in 7 steps
Episode ended in 41 steps
Episode end

In [7]:
print("Learned State-Value Function:")
print(V)

Learned State-Value Function:
[[0.00728817 0.01325942 0.02815213 0.03185166 0.02958188]
 [0.01633444 0.02986194 0.07133358 0.08553842 0.07406307]
 [0.02070572 0.03562682 0.15313382 0.46174367 0.16693124]
 [0.02014066 0.08396127 0.33799038 0.         0.36145337]
 [0.02196649 0.03314145 0.10938585 0.14864739 0.13096289]]
